# PostgreSQL Configuration (Render Production)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# IMPORTANT: Validate only (tables already exist in DB)
spring.jpa.hibernate.ddl-auto=validate

# SQL logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable init
spring.sql.init.mode=never

# Server
server.port=${PORT:8080}

spring.main.allow-circular-references=true